# Generated by Django 5.0.6 on 2024-05-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_rename_journal_entry_journalentry_entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
