# Generated by Django 5.0.6 on 2024-05-17 04:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_journalentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='journal_entry',
            new_name='entry',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
